### ISSUE TITLE
Ability to go back to previous sections of questionnaire

### ISSUE THREAD

**Issue by jywarren** [publiclab/wherewebreathe#112]
**Update:** There's no way to go back and answer Qs from entirely skipped sections -- I don't get access to the first forum even though I skipped all the questions. 

You should be able to jump back to the beginning of previous questionnaire sections; currently if you skip a whole section, that's it. Changing title to reflect this. 

@shapironick - should you be able to skip back to partially completed sections where you skipped *some* questions? Or only ones where you've skipped the whole set?

**Comment by jywarren** [comment]
Hey @shapironick - could you take a look at this issue and clarify? Thanks.

**Comment by shapironick** [comment]
I'm a little confused. I don't think users should be able to go back to sections of the original questionnaire after seeing the forums and seeing the graphs of other people's answers. I think that would erode the validity of the data as they would be primed to answer differently. or maybe i am getting your question wrong? 

although, they should be able to do the whole thing  again to track changes over time. that data won't be as valid as the original 'blind' round of survey answering but can still be valuable. 

I guess there is no real difference between doing the survey 'again' if you skipped everything and doing it again if you answered every question the first time. 

Do you think we can have some sort of design scheme to encourage people to do the survey thoroughly the first time but then allow them to have another shot to try it again, but registering that they have seen the forums and the data should be considered to have a different validity to un-primed entries?

**Comment by jywarren** [comment]
Ok, that's fine-- can you close this and make a new issue of "warn users
that they won't be able to go back if they skip Qs" and add in it "with
link explaining why" and provide a few sentences of text explaining this
that can be shown?

And mark for milestone 1.5. Thanks!

**Comment by shapironick** [comment]
This text is similar to #105
