### ISSUE TITLE
Download data produces csv filled with nonsense

### ISSUE THREAD

**Issue by mmmelissa** [publiclab/wherewebreathe#80]
Does anyone else experience this?

Not sure if its Ubuntu, LibreOffice, or the website....

**Comment by jywarren** [comment]
Closing this as we won't be providing a download via a web interface; I believe @shapironick mentioned we'd only need download every six months or so, and we'd best do this via ssh. Does that sound right to you, @mmmelissa? Could your bulk download script be adapted to be run on the commandline only?

**Comment by mmmelissa** [comment]
Maybe? If you can run JS in the shell somehow, then probably. Looks like it
would still need to be debugged, unless the problem was originating on the
client side.

On Fri, Feb 6, 2015 at 4:55 PM, Jeffrey Warren <notifications@github.com>
wrote:

> Closing this as we won't be providing a download via a web interface; I
> believe @shapironick <https://github.com/shapironick> mentioned we'd only
> need download every six months or so, and we'd best do this via ssh. Does
> that sound right to you, @mmmelissa <https://github.com/mmmelissa>? Could
> your bulk download script be adapted to be run on the commandline only?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/publiclab/wherewebreathe/issues/80#issuecomment-73340710>
> .
>



-- 
Melissa Nunes
Web Developer | Spatial IT Specialist
Skype: nunes.melissa.m
Email: nunes.melissa.m@gmail.com
Linkedin <http://ca.linkedin.com/pub/melissa-nunes/74/639/3a5>
